version: '3'
services:
  #-----------------------------------------------
  # Chrome for Selenium
  #-----------------------------------------------
  selenium:
    container_name: selenium
    image: selenium/standalone-firefox-debug:3.141.59
    ports:
      - 4444:4444
      - 5900:5900