[project]
name = "codabench"
version = "0.1.0"
description = ""
authors = [{ name = "Codalab" }]
requires-python = "==3.9.20"
readme = "README.md"
dependencies = [
    "django==3.2.0",
    "django-oauth-toolkit==1.2.0",
    "django-cors-middleware==1.5.0",
    "social-auth-core==2.0.0",
    "social-auth-app-django==3.1.0",
    "six==1.16.0",
    "django-extensions==2.2.6",
    "channels==3.0.0",
    "channels-redis==4.0.0",
    "pillow==10.3.0",
    "celery==4.4.7",
    "gunicorn==22.0.0",
    "urllib3>=1.21.1,<1.25",
    "uvicorn[standard]==0.13.3",
    "pyyaml==5.3.1",
    "watchdog==2.1.1",
    "argh==0.26.2",
    "python-dateutil==2.7.3",
    "bpython>=0.21.0,<0.22",
    "websockets==8.1",
    "aiofiles==0.4.0",
    "oyaml==0.7",
    "factory-boy==2.11.1",
    "bleach==3.1.4",
    "django-debug-toolbar==3.2",
    "django-querycount==0.7.0",
    "blessings==1.7",
    "django-su==0.9.0",
    "django-ajax-selects==2.0.0",
    "dj-database-url==0.4.2",
    "psycopg2-binary==2.8.6",
    "django-redis==4.12.1",
    "django-storages==1.9.1",
    "azure-storage-blob==2.1.0",
    "azure-storage-common==2.1.0",
    "boto3==1.9.68",
    "whitenoise==5.2.0",
    "coreapi==2.3.3",
    "djangorestframework==3.12.0",
    "djangorestframework-csv==3.0.1",
    "drf-extensions==0.4.0",
    "markdown==2.6.11",
    "pygments==2.2.0",
    "drf-writable-nested==0.6.2",
    "django-filter==2.4.0",
    "flex==6.12.0",
    "pyrabbit2==1.0.7",
    "django-enforce-host==1.0.1",
    "twisted==24.7.0",
    "ipdb==0.13",
    "flake8==3.8.4",
    "pytest==6.2.1",
    "pytest-django==4.1.0",
    "pytest-pythonpath==0.7.3",
    "jinja2==3.1.4",
    "requests==2.32.2",
    "drf-extra-fields==3.7.0",
    "drf-yasg2>=1.19.4,<2",
    "swagger-spec-validator>=3.0.4,<4",
    "loguru>=0.7.3,<0.8",
]

[tool.uv]
package = false

[build-system]
requires = ["uv_build>=0.9.16,<0.10.0"]
build-backend = "uv_build"
