apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.appState.pvcName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.appState.storage }}
  storageClassName: {{ .Values.appState.storageClass }}
