apiVersion: v1
kind: ServiceAccount
metadata:
  name: compute-worker-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: compute-worker-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec", "pods/log"]
    verbs: ["create", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: compute-worker-bind
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: compute-worker-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: compute-worker-role
  apiGroup: rbac.authorization.k8s.io
