{{- if .Values.istio.enableVirtualService}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: codabench-vs
spec:
  {{- toYaml .Values.istio.spec | nindent 12 }}

{{- else }}
{{- end }}

