apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sharedJob.pvcName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.sharedJob.storage }}
  storageClassName: {{ .Values.sharedJob.storageClass }}

