[project]
authors = [
    {name = "codalab"},
]
requires-python = "==3.9.20"
dependencies = [
    "celery==5.2.2",
    "requests~=2.32.4",
    "watchdog==2.1.1",
    "argh==0.26.2",
    "websockets==9.1",
    "aiofiles==0.4.0",
    "pyyaml==6.0.1",
    "loguru~=0.7.3",
]
name = "compute-worker"
version = "0.1.0"
description = ""
