[tool.poetry]
name = "compute-worker"
version = "0.1.0"
description = ""
authors = ["codalab"]

[tool.poetry.dependencies]
python = "^3.9"
celery = "4.4.0"
requests = "^2.20.0"
watchdog = "2.1.1"
argh = "0.26.2"
websockets = "8.1"
aiofiles = "0.4.0"
pyyaml = "5.3.1"
loguru = "^0.7.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
