name: build_CW_docker_image_branch
on:
  push:
    tags:
      - '*'
    paths:
      - Dockerfile.compute_worker
      - compute_worker/**
jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Build Image
        run: docker build -t codalab/competitions-v2-compute-worker:${{ github.ref_name }} -f Dockerfile.compute_worker .

  push:
    name: Push image to Dockerhub
    runs-on: ubuntu-latest
    steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Push image with prod release tag
          run: docker push codalab/competitions-v2-compute-worker:${{ github.ref_name }}
        - name: Change tag to latest
          run: |
            docker tag codalab/competitions-v2-compute-worker:${{ github.ref_name }} codalab/competitions-v2-compute-worker:latest
            docker push codalab/competitions-v2-compute-worker:latest
        
